---
- name: bastion host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: import variables
      include_vars: vars\bastion_setup

    - name: create a new ec2 key pair, returns generated private key
      ec2_key:
        name: my_keypair
        region: us-east-2
        register: keyout

    - debug:
        var: keyout

    - name: store the key
      copy:
       content: "{{keyout.key.private_key}}"
        dest: ./sample-key.pem
        when: keyout.changed

    - name: create security group for bastion
      ec2_group:
        Name: bastionhost-SG
        description: all0w port 22 from everywhere
        region: "{{region}}"
        vpc_id: "{{vpcoutid}}"
        rules:
          - proto: tcp
          - from_port: 22
          - to_port: 22
          - cidr_ip: "{{MYIP}}"
      register: bastion_out

    - name: creating bastion host
      ec2:
        key_name: my_keypair
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          project: Vprofile
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          project: Vprofile
        group_id: "{{bastion_out.group_id}}"
      register: bastion_image_out



